/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        //new SocketThread("52.174.151.207", 9999).start();
        new SocketThread("10.36.46.255", 9999, new CallbackApi() {
            @Override
            public Object call() {
                //make request and return response
                return null;
            }
        }).start();
    }

}